LANG = C

D = ./deps.sh   # dependency generator
PP = ./pp.sh    # pre-processor
MP = m4         # macro processor

MPFLAGS =

# GNU make stupidity
.SUFFIXES :
% : %.8o
% : %.m
% : %.deps
% : %.m4

.SUFFIXES : .8o .m .deps .m4

.m.8o :
	$(MP) $(MPFLAGS) $< >$@

.m4.deps :
	SHELL=/bin/sh MAKE="$(MAKE)" MFLAGS="$(MFLAGS)" $(D) $* >$@

.m4.m :
	$(PP) <$< >$@
